name: Feature Request
description: Suggest an idea to improve this site
title: "[Feature Request] "

body:
- type: markdown
  attributes:
    value: |
      This is only used to request new product features.
- type: textarea
  id: feature-request
  attributes:
    label: Describe the feature request
    description: Tell us what's you want and why it should be added in frp.
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered
